# Generated by Django 3.2.19 on 2023-09-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIsRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('date_send', models.DateField(null=True)),
                ('date_confirmed', models.DateField(null=True)),
                ('date_canceled', models.DateField(null=True)),
                ('attachment_confirm', models.FileField(blank=True, null=True, upload_to='epis_requests/%Y/%m/%d')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado'), ('PROVISORIO', 'Provisorio')], default='ABERTO', max_length=12)),
                ('author_cancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epis_requests_cancel', to='employees.employees')),
                ('author_confirm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epis_requests_confirm', to='employees.employees')),
                ('author_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_requests_create', to='employees.employees')),
                ('author_send', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epis_requests_send', to='employees.employees')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_requests', to='branches.branches')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_requests', to='employees.employees')),
            ],
            options={
                'verbose_name': 'EPIRequest',
                'verbose_name_plural': 'EPIsRequests',
                'db_table': 'epis_requests',
            },
        ),
    ]
