# Generated by Django 3.2.19 on 2023-08-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episrequests',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=12),
        ),
    ]
