# Generated by Django 3.2.19 on 2023-08-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employees_dismissal'),
        ('epis_requests', '0002_episrequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='episrequests',
            name='author_send',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epis_requests_send', to='employees.employees'),
        ),
    ]
