# Generated by Django 3.2.19 on 2023-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis_requests', '0003_episrequests_author_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episrequests',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado'), ('PROVISORIO', 'Provisorio')], default='ABERTO', max_length=12),
        ),
    ]
