# Generated by Django 3.2.19 on 2023-08-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employees_dismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetsAvailabilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_occurrence', models.DateTimeField(auto_now=True)),
                ('date_forecast', models.DateTimeField(null=True)),
                ('date_release', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PARADO', 'Parado'), ('PREVENTIVO', 'Preventivo'), ('LIBERADO', 'Liberado')], max_length=10)),
                ('service_order', models.CharField(max_length=15, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets_availabilities', to='employees.employees')),
            ],
            options={
                'verbose_name': 'FleetAvailability',
                'verbose_name_plural': 'FleetsAvailabilities',
                'db_table': 'fleets_availabilities',
            },
        ),
    ]
