# Generated by Django 4.2.5 on 2023-10-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleets_availabilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleetsavailabilities",
            name="date_forecast",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="fleetsavailabilities",
            name="date_occurrence",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fleetsavailabilities",
            name="date_release",
            field=models.DateField(null=True),
        ),
    ]
