# Generated by Django 4.2.5 on 2023-10-23 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "fleets_availabilities",
            "0002_alter_fleetsavailabilities_date_forecast_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleetsavailabilities",
            name="date_occurrence",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
