# Generated by Django 3.2.19 on 2023-09-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_availabilities', '0002_alter_fleetsavailabilities_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetsavailabilities',
            name='service_order',
            field=models.IntegerField(null=True),
        ),
    ]
