# Generated by Django 4.2.5 on 2023-10-23 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleets_availabilities", "0003_alter_fleetsavailabilities_date_occurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleetsavailabilities",
            name="date_occurrence",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
