# Generated by Django 3.2.19 on 2023-08-09 10:56

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='active',
        ),
        migrations.AddField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('DEMITIDO', 'Demitido'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, validators=[employees.models.only_int]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='cpf',
            field=models.CharField(max_length=11, null=True, validators=[employees.models.only_int]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rg',
            field=models.CharField(max_length=8, null=True, validators=[employees.models.only_int]),
        ),
    ]
