# Generated by Django 4.2.5 on 2023-10-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
