# Generated by Django 3.2.19 on 2023-08-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees_dismissals', '0001_initial'),
        ('employees', '0002_auto_20230809_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='dismissal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees_dismissals.employeesdismissals', unique=True),
        ),
    ]
