# Generated by Django 3.2.19 on 2023-08-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees_dismissals', '0001_initial'),
        ('employees', '0003_employees_dismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='dismissal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees_dismissals.employeesdismissals'),
        ),
    ]
