# Generated by Django 3.2.19 on 2023-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJBonus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor_pagamento', models.IntegerField()),
                ('data_pagamento', models.DateField()),
                ('observacao', models.TextField()),
                ('quitado', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_quitacao', models.DateField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pj_bonus_autor', to='funcionarios.funcionarios')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pj_bonus_funcionario', to='funcionarios.funcionarios')),
            ],
            options={
                'verbose_name': 'PJBonus',
                'verbose_name_plural': 'PJBonus',
                'db_table': 'pj_bonus',
            },
        ),
    ]
