# Generated by Django 3.2.19 on 2023-06-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJBonus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor_pagamento', models.IntegerField()),
                ('data_pagamento', models.DateField()),
                ('observacao', models.TextField()),
                ('quitado', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_quitacao', models.DateField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionarios')),
            ],
        ),
    ]
