# Generated by Django 3.2.19 on 2023-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesEPIs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('phone_model', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_code', models.IntegerField(blank=True, null=True)),
                ('notebook_model', models.CharField(blank=True, max_length=50, null=True)),
                ('notebook_code', models.IntegerField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EmployeeEPI',
                'verbose_name_plural': 'EmployeesEPIs',
                'db_table': 'employees_epis',
            },
        ),
    ]
