# Generated by Django 3.2.19 on 2023-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_epis', '0003_auto_20230811_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesepis',
            name='notebook_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeesepis',
            name='notebook_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeesepis',
            name='phone_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeesepis',
            name='phone_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
