# Generated by Django 3.2.19 on 2023-07-31 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funcionarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiais', '0001_initial'),
        ('pj_complementos', '0001_initial'),
        ('funcionarios_epis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('genero', models.CharField(choices=[('HOMEM CISGÊNERO', 'Homem Cisgenero'), ('HOMEM TRANSGÊNERO', 'Homem Transgenero'), ('MULHER CISGÊNERO', 'Mulher Cisgenero'), ('MULHER TRANSGÊNERO', 'Mulher Transgenero'), ('NÃO BINÁRIO', 'Nao Binario'), ('NÃO QUERO INFORMAR', 'Nao Quero Informar')], max_length=25, null=True)),
                ('data_nascimento', models.DateField(null=True)),
                ('rg', models.CharField(max_length=8, null=True, unique=True, validators=[funcionarios.models.only_int])),
                ('cpf', models.CharField(max_length=11, null=True, unique=True, validators=[funcionarios.models.only_int])),
                ('cnpj', models.CharField(max_length=14, null=True, unique=True, validators=[funcionarios.models.only_int])),
                ('empresa', models.CharField(choices=[('BORA', 'Bora'), ('BORBON', 'Borbon'), ('JC', 'Jc'), ('JSR', 'Jsr'), ('TRANSFOOD', 'Transfood')], max_length=15)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'Clt'), ('PJ', 'Pj')], max_length=3)),
                ('cargo', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=7, null=True, validators=[funcionarios.models.only_int])),
                ('complemento', models.CharField(blank=True, max_length=75, null=True)),
                ('cep', models.CharField(max_length=8, null=True, validators=[funcionarios.models.only_int])),
                ('bairro', models.CharField(max_length=50, null=True)),
                ('cidade', models.CharField(max_length=30, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('banco', models.CharField(max_length=20, null=True)),
                ('agencia', models.CharField(max_length=5, null=True, validators=[funcionarios.models.only_int])),
                ('conta', models.CharField(max_length=15, null=True, validators=[funcionarios.models.only_int])),
                ('operacao', models.IntegerField(null=True)),
                ('pix', models.CharField(max_length=30, null=True)),
                ('data_admissao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('primeiro_acesso', models.BooleanField(default=True)),
                ('epi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='funcionarios_epis.funcionariosepis')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='filiais.filiais')),
                ('pj_complementos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='pj_complementos.pjcomplementos')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'funcionarios',
            },
        ),
    ]
