# Generated by Django 3.2.19 on 2023-06-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funcionarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiais', '0002_auto_20230508_0943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pj_complementos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('genero', models.CharField(choices=[('CISGÊNERO', 'Cisgenero'), ('TRANSGÊNERO', 'Transgenero'), ('NÃO BINÁRIO', 'Nao Binario')], max_length=15)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(max_length=8, unique=True, validators=[funcionarios.models.only_int])),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[funcionarios.models.only_int])),
                ('cnpj', models.CharField(max_length=14, null=True, unique=True, validators=[funcionarios.models.only_int])),
                ('empresa', models.CharField(choices=[('BORA', 'Bora'), ('BORBON', 'Borbon'), ('JSR', 'Jsr'), ('TRANSFOOD', 'Transfood'), ('JC', 'Jc')], max_length=15)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'Clt'), ('PJ', 'Pj')], max_length=3)),
                ('cargo', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=7, validators=[funcionarios.models.only_int])),
                ('complemento', models.CharField(blank=True, max_length=75, null=True)),
                ('cep', models.CharField(max_length=8, validators=[funcionarios.models.only_int])),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('banco', models.CharField(max_length=3, validators=[funcionarios.models.only_int])),
                ('ag', models.CharField(max_length=5, validators=[funcionarios.models.only_int])),
                ('conta', models.CharField(max_length=15, validators=[funcionarios.models.only_int])),
                ('pix', models.CharField(max_length=20)),
                ('data_admissao', models.DateField()),
                ('complemento_funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='pj_complementos.pjcomplementos')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='filiais.filiais')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'funcionarios',
            },
        ),
    ]
