# Generated by Django 3.2.19 on 2023-06-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='ag',
            new_name='agencia',
        ),
    ]
