# Generated by Django 3.2.19 on 2023-06-29 07:58

from django.db import migrations, models
import funcionarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20230627_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='operacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='agencia',
            field=models.CharField(max_length=5, null=True, validators=[funcionarios.models.only_int]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='banco',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cep',
            field=models.CharField(max_length=8, null=True, validators=[funcionarios.models.only_int]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cidade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='conta',
            field=models.CharField(max_length=15, null=True, validators=[funcionarios.models.only_int]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[funcionarios.models.only_int]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='numero',
            field=models.CharField(max_length=7, null=True, validators=[funcionarios.models.only_int]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='pix',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='rua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
