# Generated by Django 3.2.19 on 2023-06-29 11:11

from django.db import migrations, models
import funcionarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20230629_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='empresa',
            field=models.CharField(choices=[('BORA', 'Bora'), ('BORBON', 'Borbon'), ('JC', 'Jc'), ('JSR', 'Jsr'), ('TRANSFOOD', 'Transfood')], max_length=15),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='genero',
            field=models.CharField(choices=[('CISGÊNERO', 'Cisgenero'), ('TRANSGÊNERO', 'Transgenero'), ('NÃO BINÁRIO', 'Nao Binario')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='rg',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[funcionarios.models.only_int]),
        ),
    ]
