# Generated by Django 4.2.5 on 2023-11-03 13:52

import deliveries_histories.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_employees_email"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveriesHistories",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "cte",
                    models.CharField(
                        max_length=15, validators=[deliveries_histories.models.only_int]
                    ),
                ),
                ("date_emission", models.DateField()),
                ("lead_time", models.DateField()),
                ("date_delivery", models.DateField()),
                ("recipient", models.CharField(max_length=200)),
                ("sender", models.CharField(max_length=200)),
                ("delivery_location", models.CharField(max_length=100)),
                ("weight", models.FloatField(default=0)),
                ("opened", models.SmallIntegerField(default=0)),
                ("nf", models.TextField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[("NFS", "Nfs"), ("CTE", "Cte")], max_length=3
                    ),
                ),
                (
                    "description_justification",
                    models.CharField(
                        choices=[
                            ("FERIADO NACIONAL", "Feriado Nacional"),
                            (
                                "FERIADOS MUNICIPAIS / ESTADUAIS",
                                "Feriados Municipais Estaduais",
                            ),
                            ("ENTREGA AGENDADA", "Entrega Agendada"),
                            (
                                "CLIENTE COM RETENÇÃO FISCAL",
                                "Cliente Com Retenção Fiscal",
                            ),
                            (
                                "DESTINATARIO NÃO RECEBEU O XML",
                                "Destinatario Não Recebeu O Xml",
                            ),
                            ("NF SEM PEDIDO", "Nf Sem Pedido"),
                            ("PEDIDO EXPIRADO", "Pedido Expirado"),
                            ("EXCESSO DE VEICULOS", "Excesso De Veiculos"),
                            ("GRADE FIXA", "Grade Fixa"),
                            ("DEVOLUÇÃO TOTAL ", "Devolução Total"),
                            ("ATRASO NA TRANSFERENCIA", "Atraso Na Transferencia"),
                            ("CUSTO", "Custo"),
                            ("ENTREGUE SEM LEAD TIME", "Entregue Sem Lead Time"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(null=True, upload_to="justification/%Y/%m/%d"),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("refuse", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries_histories",
                        to="employees.employees",
                    ),
                ),
                (
                    "author_responsible",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries_histories_responsible",
                        to="employees.employees",
                    ),
                ),
                (
                    "branch_destination",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries_histories_destination",
                        to="branches.branches",
                    ),
                ),
                (
                    "branch_issuing",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries_histories_issuing",
                        to="branches.branches",
                    ),
                ),
            ],
            options={
                "verbose_name": "DeliveryHistory",
                "verbose_name_plural": "DeliveriesHistories",
                "db_table": "deliveries_histories",
            },
        ),
    ]
