# Generated by Django 3.2.19 on 2023-08-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries_histories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverieshistories',
            old_name='cte',
            new_name='code',
        ),
    ]
