# Generated by Django 4.2.5 on 2023-10-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employees_email"),
        ("deliveries_histories", "0002_rename_code_deliverieshistories_cte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverieshistories",
            name="author_responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries_histories_responsible",
                to="employees.employees",
            ),
        ),
    ]
