# Generated by Django 4.2.5 on 2023-11-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
        ("deliveries_histories", "0003_deliverieshistories_author_responsible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverieshistories",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="deliverieshistories",
            name="garage",
        ),
        migrations.RemoveField(
            model_name="deliverieshistories",
            name="id_garage",
        ),
        migrations.AddField(
            model_name="deliverieshistories",
            name="branch_destination",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries_histories_destination",
                to="branches.branches",
            ),
        ),
        migrations.AddField(
            model_name="deliverieshistories",
            name="branch_issuing",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries_histories_issuing",
                to="branches.branches",
            ),
        ),
    ]
