# Generated by Django 3.2.19 on 2023-07-05 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionarios', '0007_alter_funcionarios_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJContratos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('inicio_contrato', models.DateField()),
                ('final_contrato', models.DateField()),
                ('data_reajuste', models.DateField()),
                ('valor_reajuste', models.IntegerField(null=True)),
                ('anexo', models.FileField(null=True, upload_to='contratos/%Y/%m/%d')),
                ('observacao', models.TextField(null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionarios')),
            ],
            options={
                'verbose_name': 'PJContrato',
                'verbose_name_plural': 'PJContratos',
                'db_table': 'pj_contratos',
            },
        ),
    ]
