# Generated by Django 3.2.19 on 2023-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjcontratos',
            name='valor_reajuste',
            field=models.IntegerField(),
        ),
    ]
