# Generated by Django 3.2.19 on 2023-07-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_funcionarios_genero'),
        ('pj_contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjcontratos',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pj_contratos', to='funcionarios.funcionarios', unique=True),
        ),
    ]
