# Generated by Django 3.2.19 on 2023-06-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJDecimosTerceiros',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('periodo_meses', models.IntegerField()),
                ('parcela_1', models.DateField()),
                ('parcela_2', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decimo_terceiro', to='funcionarios.funcionarios')),
            ],
            options={
                'verbose_name': 'PJDecimoTerceiro',
                'verbose_name_plural': 'PJDecimosTerceiros',
                'db_table': 'pj_decimos_terceiros',
            },
        ),
    ]
