# Generated by Django 3.2.19 on 2023-05-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiais',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
        migrations.AlterModelTable(
            name='filiais',
            table='filiais',
        ),
    ]
