# Generated by Django 3.2.19 on 2023-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiais',
            name='empresa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
