# Generated by Django 3.2.19 on 2023-09-05 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('purchases_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesEntries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('observation', models.TextField()),
                ('file_1', models.FileField(blank=True, null=True, upload_to='purchases_entries/%Y/%m/%d')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='purchases_entries/%Y/%m/%d')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='purchases_entries/%Y/%m/%d')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_entries', to='employees.employees')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_requests.purchasesrequests')),
            ],
            options={
                'verbose_name': 'PurchaseEntry',
                'verbose_name_plural': 'PurchasesEntries',
                'db_table': 'purchases_entries',
            },
        ),
    ]
