# Generated by Django 4.2.5 on 2023-10-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("purchases_requests", "0003_alter_purchasesrequests_department"),
        ("purchases_entries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasesentries",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases_entries",
                to="purchases_requests.purchasesrequests",
            ),
        ),
    ]
