# Generated by Django 3.2.19 on 2023-08-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('document', models.CharField(max_length=14, unique=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('type_registration', models.CharField(choices=[('CLIENTE', 'Cliente'), ('MOTORISTA', 'Motorista')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='employees.employees')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientsBranches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('type_pallet', models.CharField(choices=[('PBR', 'Pbr'), ('CHEP', 'Chep')], default='PBR', max_length=4)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branches')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
            options={
                'verbose_name': 'ClientBranch',
                'verbose_name_plural': 'ClientsBranches',
                'db_table': 'clients_branches',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='branches',
            field=models.ManyToManyField(through='clients.ClientsBranches', to='branches.Branches', verbose_name='clients'),
        ),
    ]
