# Generated by Django 3.2.19 on 2023-09-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsbranches',
            name='type_pallet',
        ),
    ]
