# Generated by Django 3.2.19 on 2023-09-02 21:37

from django.db import migrations, models
import payments_histories.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsHistories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('cnpj', models.CharField(max_length=14, null=True, validators=[payments_histories.models.only_int])),
                ('bank', models.CharField(max_length=20, null=True)),
                ('agency', models.CharField(max_length=5, null=True, validators=[payments_histories.models.only_int])),
                ('account', models.CharField(max_length=25, null=True, validators=[payments_histories.models.only_int])),
                ('operation', models.IntegerField(null=True)),
                ('pix', models.CharField(max_length=30, null=True)),
                ('salary', models.FloatField()),
                ('allowance', models.FloatField(default=0)),
                ('college', models.FloatField(default=0)),
                ('housing_allowance', models.FloatField(default=0)),
                ('covenant_credit', models.FloatField(default=0)),
                ('others_credits', models.FloatField(default=0)),
                ('advance_money', models.FloatField(default=0)),
                ('covenant_discount', models.FloatField(default=0)),
                ('others_discounts', models.FloatField(default=0)),
                ('data_emission', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PaymentHistory',
                'verbose_name_plural': 'PaymentsHistories',
                'db_table': 'payments_histories',
            },
        ),
    ]
