# Generated by Django 4.2.5 on 2023-11-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments_histories", "0003_remove_paymentshistories_data_emission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentshistories",
            name="data_emission",
            field=models.DateField(auto_now=True),
        ),
    ]
