# Generated by Django 4.2.5 on 2023-11-24 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments_histories", "0004_paymentshistories_data_emission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentshistories",
            old_name="data_emission",
            new_name="date_emission",
        ),
    ]
