# Generated by Django 4.2.5 on 2023-11-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries_histories", "0004_remove_deliverieshistories_branch_and_more"),
        ("occurrences", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrences",
            name="cte",
        ),
        migrations.RemoveField(
            model_name="occurrences",
            name="garage",
        ),
        migrations.AlterField(
            model_name="occurrences",
            name="justification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="deliveries_histories.deliverieshistories",
            ),
        ),
    ]
