# Generated by Django 3.2.19 on 2023-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletesMovimentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('solicitacao', models.CharField(max_length=25)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_recebimento', models.DateTimeField(null=True)),
                ('placa_veiculo', models.CharField(max_length=7)),
                ('motorista', models.CharField(max_length=35)),
                ('conferente', models.CharField(max_length=35)),
                ('recebido', models.BooleanField(default=False)),
                ('quantidade_paletes', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paletes_movimentos', to='funcionarios.funcionarios')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paletes_movimentos_destino', to='filiais.filiais')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paletes_movimentos_origem', to='filiais.filiais')),
            ],
            options={
                'verbose_name': 'PaleteMovimento',
                'verbose_name_plural': 'PaletesMovimentos',
                'db_table': 'paletes_movimentos',
            },
        ),
    ]
