# Generated by Django 3.2.19 on 2023-08-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employees_dismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIsCarts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_carts', to='employees.employees')),
            ],
            options={
                'verbose_name': 'EPICart',
                'verbose_name_plural': 'EPIsCarts',
                'db_table': 'epis_carts',
            },
        ),
    ]
