# Generated by Django 3.2.19 on 2023-09-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epis_sizes', '0001_initial'),
        ('epis_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIsCarts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_carts', to='epis_requests.episrequests')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_carts', to='epis_sizes.epissizes')),
            ],
            options={
                'verbose_name': 'EPICart',
                'verbose_name_plural': 'EPIsCarts',
                'db_table': 'epis_carts',
            },
        ),
    ]
