# Generated by Django 3.2.19 on 2023-08-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epis_requests', '0001_initial'),
        ('epis_sizes', '0001_initial'),
        ('epis_carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episcarts',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_carts', to='epis_requests.episrequests'),
        ),
        migrations.AddField(
            model_name='episcarts',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_carts', to='epis_sizes.epissizes'),
        ),
    ]
