# Generated by Django 3.2.19 on 2023-08-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epis_carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episcarts',
            name='author',
        ),
    ]
