# Generated by Django 3.2.19 on 2023-06-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_pagamento', models.DateField()),
                ('mensagem', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='funcionarios.funcionarios')),
            ],
            options={
                'verbose_name': 'PJEmail',
                'verbose_name_plural': 'PJEmails',
                'db_table': 'pj_emails',
            },
        ),
    ]
