# Generated by Django 3.2.19 on 2023-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionariosEPIs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('celular_modelo', models.CharField(max_length=50, null=True, unique=True)),
                ('celular_numero_ativo', models.IntegerField(null=True, unique=True)),
                ('notebook_modelo', models.IntegerField(null=True, unique=True)),
                ('notebook_numero_ativo', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'FuncionarioEPI',
                'verbose_name_plural': 'FuncionariosEPIs',
                'db_table': 'funcionarios_epis',
            },
        ),
    ]
