# Generated by Django 3.2.19 on 2023-05-31 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitacoes_compras', '0003_auto_20230531_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesEntradas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('obs', models.TextField()),
                ('arquivo_1', models.FileField(blank=True, null=True, upload_to='compras/%Y/%m/%d')),
                ('arquivo_2', models.FileField(blank=True, null=True, upload_to='compras/%Y/%m/%d')),
                ('arquivo_3', models.FileField(blank=True, null=True, upload_to='compras/%Y/%m/%d')),
                ('data_criacao', models.DateField(default=datetime.date(2023, 5, 31))),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes_compras.solicitacoescompras')),
            ],
            options={
                'verbose_name': 'SolicitacaoEntrada',
                'verbose_name_plural': 'SolicitacoesEntradas',
                'db_table': 'solicitacoes_entradas',
            },
        ),
    ]
