# Generated by Django 3.2.19 on 2023-05-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_entradas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacoesentradas',
            old_name='obs',
            new_name='observacao',
        ),
    ]
