# Generated by Django 3.2.19 on 2023-06-12 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_entradas', '0002_rename_obs_solicitacoesentradas_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoesentradas',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
