# Generated by Django 4.2.5 on 2023-10-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_employees_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manuals",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="manuals/%Y/%m/%d")),
                ("system", models.CharField(max_length=50)),
                ("module", models.CharField(max_length=50)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manuals",
                        to="employees.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual",
                "verbose_name_plural": "Manuals",
                "db_table": "manuals",
            },
        ),
    ]
