# Generated by Django 4.2.5 on 2023-10-05 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skus", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skus",
            old_name="description",
            new_name="discount_product",
        ),
    ]
