# Generated by Django 3.2.19 on 2023-08-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epis_groups', '0001_initial'),
        ('employees', '0004_alter_employees_dismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIsItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='UNICO', max_length=5)),
                ('validity', models.DateField()),
                ('ca', models.CharField(max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_items', to='employees.employees')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_items', to='epis_groups.episgroups')),
            ],
            options={
                'verbose_name': 'EPIItem',
                'verbose_name_plural': 'EPIsItems',
                'db_table': 'epis_items',
            },
        ),
    ]
