# Generated by Django 3.2.19 on 2023-09-07 14:16

from django.db import migrations, models
import django.db.models.deletion
import epis_items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('epis_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIsItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('validity', models.DateField()),
                ('time_for_use', models.CharField(blank=True, default=365, max_length=3, null=True, validators=[epis_items.models.only_int])),
                ('ca', models.CharField(blank=True, max_length=15, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_items', to='employees.employees')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_items', to='epis_groups.episgroups')),
            ],
            options={
                'verbose_name': 'EPIItem',
                'verbose_name_plural': 'EPIsItems',
                'db_table': 'epis_items',
            },
        ),
    ]
