# Generated by Django 3.2.19 on 2023-08-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episitems',
            name='ca',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='episitems',
            name='description',
            field=models.CharField(default='UNICO', max_length=50),
        ),
    ]
