# Generated by Django 3.2.19 on 2023-08-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis_items', '0002_auto_20230825_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episitems',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
