# Generated by Django 3.2.19 on 2023-08-30 12:50

from django.db import migrations, models
import epis_items.models


class Migration(migrations.Migration):

    dependencies = [
        ('epis_items', '0003_alter_episitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='episitems',
            name='time_for_use',
            field=models.CharField(default=365, max_length=3, validators=[epis_items.models.only_int]),
        ),
    ]
