# Generated by Django 3.2.19 on 2023-09-05 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletsMovements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('request', models.CharField(max_length=25)),
                ('date_request', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_received', models.DateTimeField(null=True)),
                ('vehicle_plate', models.CharField(max_length=7)),
                ('driver', models.CharField(max_length=35)),
                ('checker', models.CharField(max_length=35)),
                ('received', models.BooleanField(default=False)),
                ('quantity_pallets', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets_movements', to='employees.employees')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets_movements_destiny', to='branches.branches')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets_movements_origin', to='branches.branches')),
            ],
            options={
                'verbose_name': 'PalletMovement',
                'verbose_name_plural': 'PalletsMovements',
                'db_table': 'pallets_movements',
            },
        ),
    ]
