# Generated by Django 3.2.19 on 2023-09-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesrequests',
            name='latest_updater',
        ),
    ]
