# Generated by Django 4.2.5 on 2023-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases_requests", "0002_alter_purchasesrequests_requester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasesrequests",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAO INFORMADO", "Default"),
                    ("DIRETORIA", "Diretoria"),
                    ("FATURAMENTO", "Faturamento"),
                    ("FINANCEIRO", "Financeiro"),
                    ("RH", "Rh"),
                    ("FISCAL", "Fiscal"),
                    ("MONITORAMENTO", "Monitoramento"),
                    ("OPERACIONAL", "Operacional"),
                    ("FROTA", "Frota"),
                    ("EXPEDICAO", "Expedicao"),
                    ("COMERCIAL", "Comercial"),
                    ("MARKETING", "Marketing"),
                    ("JURIDICO", "Juridico"),
                    ("DESENVOLVIMENTO", "Desenvolvimento"),
                    ("TI", "Ti"),
                    ("FILIAIS", "Filiais"),
                    ("COMPRAS", "Compras"),
                ],
                default="NAO INFORMADO",
                max_length=30,
                null=True,
            ),
        ),
    ]
