# Generated by Django 3.2.19 on 2023-09-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('purchases_requests', '0002_remove_purchasesrequests_latest_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesrequests',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_authors', to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='purchasesrequests',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_requesters', to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='purchasesrequests',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_responsible', to='employees.employees'),
        ),
    ]
