# Generated by Django 3.2.19 on 2023-05-18 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filiais', '0002_auto_20230508_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numero_solicitacao', models.IntegerField(unique=True)),
                ('data_solicitacao_bo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vencimento_boleto', models.DateField(blank=True, null=True)),
                ('data_conclusao_pedido', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], max_length=30)),
                ('departamento', models.CharField(blank=True, choices=[('NÃO INFORMADO', 'Default'), ('DIRETORIA', 'Diretoria'), ('FATURAMENTO', 'Faturamento'), ('FINANCEIRO', 'Financeiro'), ('RH', 'Rh'), ('FISCAL', 'Fiscal'), ('MONITORAMENTO', 'Monitoramento'), ('OPERACIONAL', 'Operacional'), ('FROTA', 'Frota'), ('EXPEDICAO', 'Expedicao'), ('COMERCIAL', 'Comercial'), ('JURIDICO', 'Juridico'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('TI', 'Ti'), ('FILIAIS', 'Filiais'), ('COMPRAS', 'Compras')], default='NÃO INFORMADO', max_length=30, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('NÃO INFORMADO', 'Default'), ('ALMOXARIFADO', 'Almoxarifado'), ('COTACAO', 'Cotacao'), ('NOTA FISCAL', 'Nota Fiscal')], default='NÃO INFORMADO', max_length=30, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('NÃO INFORMADO', 'Default'), ('A VISTA', 'A Vista'), ('PARCELADO 1X', 'Parcelado 1X'), ('PARCELADO 2X', 'Parcelado 2X'), ('PARCELADO 3X', 'Parcelado 3X'), ('PARCELADO 4X', 'Parcelado 4X'), ('PARCELADO 5X', 'Parcelado 5X'), ('PARCELADO 6X', 'Parcelado 6X'), ('PARCELADO 7X', 'Parcelado 7X'), ('PARCELADO 8X', 'Parcelado 8X'), ('PARCELADO 9X', 'Parcelado 9X'), ('PARCELADO 10X', 'Parcelado 10X'), ('PARCELADO 11X', 'Parcelado 11X'), ('PARCELADO 12X', 'Parcelado 12X')], default='NÃO INFORMADO', max_length=30, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='cpr/%Y/%m/%d')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_autor', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compras', to='filiais.filiais')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_responsavel', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_solicitante', to=settings.AUTH_USER_MODEL)),
                ('ultima_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_ultima_att', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SolicitacaoCompra',
                'verbose_name_plural': 'SolicitacoesCompras',
                'db_table': 'solicitacoes_compras',
            },
        ),
    ]
