# Generated by Django 3.2.19 on 2023-05-05 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numero_solicitacao', models.IntegerField(unique=True)),
                ('data_solicitacao_pra', models.DateField()),
                ('data_solicitacao_bo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vencimento_boleto', models.DateField(blank=True, null=True)),
                ('data_conclusao_pedido', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'ABERTO'), ('ANDAMENTO', 'ANDAMENTO'), ('CONCLUIDO', 'CONCLUIDO'), ('CANCELADO', 'CANCELADO')], max_length=30)),
                ('departamento', models.CharField(blank=True, choices=[('DIRETORIA', 'DIRETORIA'), ('FATURAMENTO', 'FATURAMENTO'), ('FINANCEIRO', 'FINANCEIRO'), ('RH', 'RH'), ('FISCAL', 'FISCAL'), ('MONITORAMENTO', 'MONITORAMENTO'), ('OPERACIONAL', 'OPERACIONAL'), ('FROTA', 'FROTA'), ('EXPEDICAO', 'EXPEDICAO'), ('COMERCIAL', 'COMERCIAL'), ('JURIDICO', 'JURIDICO'), ('DESENVOLVIMENTO', 'DESENVOLVIMENTO'), ('TI', 'TI'), ('FILIAIS', 'FILIAIS'), ('COMPRAS', 'COMPRAS'), ('DEFAULT', 'NÃO INFORMADO'), ('DEFAULT', 'NÃO INFORMADO')], max_length=30, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('COTACAO', 'COTACAO'), ('NOTA FISCAL', 'NOTA FISCAL'), ('DEFAULT', 'NÃO INFORMADO')], max_length=30, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('A_VISTA', 'A VISTA'), ('PARCELADO-1X', 'PARCELADO 1X'), ('PARCELADO-2X', 'PARCELADO 2X'), ('PARCELADO-3X', 'PARCELADO 3X'), ('PARCELADO-4X', 'PARCELADO 4X'), ('PARCELADO-5X', 'PARCELADO 5X'), ('PARCELADO-6X', 'PARCELADO 6X'), ('PARCELADO-7X', 'PARCELADO 7X'), ('PARCELADO-8X', 'PARCELADO 8X'), ('PARCELADO-9X', 'PARCELADO 9X'), ('PARCELADO-10X', 'PARCELADO 10X'), ('PARCELADO-11X', 'PARCELADO 11X'), ('PARCELADO-12X', 'PARCELADO 12X'), ('DEFAULT', 'NÃO INFORMADO')], max_length=30, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='cpr/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'SolicitacaoCompra',
                'verbose_name_plural': 'SolicitacoesCompras',
                'db_table': 'solicitacoes_compras',
            },
        ),
    ]
