# Generated by Django 3.2.19 on 2023-05-31 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='data_solicitacao_bo',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 9, 17, 31, 328201)),
        ),
    ]
