# Generated by Django 3.2.19 on 2023-07-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('solicitacoes_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_solicitante', to='funcionarios.funcionarios'),
        ),
    ]
