# Generated by Django 3.2.19 on 2023-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ALMOXARIFADO', 'Almoxarifado'), ('COTACAO', 'Cotacao'), ('NOTA FISCAL', 'Nota Fiscal'), ('NÃO INFORMADO', 'Default')], default='NÃO INFORMADO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='departamento',
            field=models.CharField(blank=True, choices=[('DIRETORIA', 'Diretoria'), ('FATURAMENTO', 'Faturamento'), ('FINANCEIRO', 'Financeiro'), ('RH', 'Rh'), ('FISCAL', 'Fiscal'), ('MONITORAMENTO', 'Monitoramento'), ('OPERACIONAL', 'Operacional'), ('FROTA', 'Frota'), ('EXPEDICAO', 'Expedicao'), ('COMERCIAL', 'Comercial'), ('JURIDICO', 'Juridico'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('TI', 'Ti'), ('FILIAIS', 'Filiais'), ('COMPRAS', 'Compras'), ('NÃO INFORMADO', 'Default')], default='NÃO INFORMADO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('A VISTA', 'A Vista'), ('PARCELADO 1X', 'Parcelado 1X'), ('PARCELADO 2X', 'Parcelado 2X'), ('PARCELADO 3X', 'Parcelado 3X'), ('PARCELADO 4X', 'Parcelado 4X'), ('PARCELADO 5X', 'Parcelado 5X'), ('PARCELADO 6X', 'Parcelado 6X'), ('PARCELADO 7X', 'Parcelado 7X'), ('PARCELADO 8X', 'Parcelado 8X'), ('PARCELADO 9X', 'Parcelado 9X'), ('PARCELADO 10X', 'Parcelado 10X'), ('PARCELADO 11X', 'Parcelado 11X'), ('PARCELADO 12X', 'Parcelado 12X'), ('NÃO INFORMADO', 'Default')], default='NÃO INFORMADO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], max_length=30),
        ),
    ]
