# Generated by Django 3.2.19 on 2023-05-08 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filiais', '0001_initial'),
        ('solicitacoes_compras', '0002_auto_20230505_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoescompras',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacoescompras',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compras', to='filiais.filiais'),
        ),
        migrations.AddField(
            model_name='solicitacoescompras',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacoescompras',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_solicitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacoescompras',
            name='ultima_atualizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_ultima_att', to=settings.AUTH_USER_MODEL),
        ),
    ]
