# Generated by Django 3.2.19 on 2023-05-31 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes_compras', '0002_alter_solicitacoescompras_data_solicitacao_bo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='compras/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='data_solicitacao_bo',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 15, 34, 47, 674950)),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='ultima_atualizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_ultima_att', to=settings.AUTH_USER_MODEL),
        ),
    ]
