# Generated by Django 3.2.19 on 2023-06-01 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_compras', '0004_alter_solicitacoescompras_data_solicitacao_bo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='data_solicitacao_bo',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 12, 23, 49, 599099)),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=30),
        ),
    ]
