# Generated by Django 3.2.19 on 2023-07-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_funcionarios_genero'),
        ('solicitacoes_compras', '0005_auto_20230729_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_solicitante', to='funcionarios.funcionarios'),
        ),
    ]
