# Generated by Django 3.2.19 on 2023-06-09 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_compras', '0005_auto_20230601_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='data_solicitacao_bo',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 17, 21, 52, 486899)),
        ),
    ]
