# Generated by Django 3.2.19 on 2023-06-09 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_compras', '0006_alter_solicitacoescompras_data_solicitacao_bo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='data_solicitacao_bo',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 17, 22, 27, 811589)),
        ),
    ]
