# Generated by Django 3.2.19 on 2023-09-05 15:12

from django.db import migrations, models
import django.db.models.deletion
import vehicles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type_vehicle', models.CharField(choices=[('VAN-PASSAGEIROS', 'Van Passageiros'), ('CAMINHAO', 'Caminhao'), ('CAVALO', 'Cavalo'), ('CARRETA', 'Carreta'), ('VUC-MINI CAMINHAO', 'Vuc Mini Caminhao'), ('BI TRUCK', 'Bi Truck'), ('TOCO', 'Toco'), ('3/4', 'Tres Quartos'), ('TRUCK', 'Truck'), ('VEICULO APOIO', 'Veiculo Apoio'), ('PASSAGEIRO', 'Passageiro'), ('PASSAGEIRO MOVEL', 'Passageiro Movel'), ('VW/24.280 CRM 6X2', 'Vw 24 280 Crm 6X2'), ('FIORINO', 'Fiorino'), ('HR', 'Hr')], max_length=20, null=True)),
                ('vehicle_plate', models.CharField(max_length=7, unique=True)),
                ('vehicle_mileage', models.IntegerField()),
                ('renavam', models.CharField(max_length=11, validators=[vehicles.models.only_int])),
                ('model_vehicle', models.CharField(max_length=20)),
                ('observation', models.CharField(blank=True, max_length=50, null=True)),
                ('last_movement', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='branches.branches')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
            },
        ),
    ]
