# Generated by Django 4.2.5 on 2023-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicles",
            name="last_movement",
            field=models.IntegerField(null=True),
        ),
    ]
