# Generated by Django 3.2.19 on 2023-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicles_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='type_vehicle',
            field=models.CharField(choices=[('VAN-PASSAGEIROS', 'Van Passageiros'), ('CAMINHAO', 'Caminhao'), ('CAVALO', 'Cavalo'), ('CARRETA', 'Carreta'), ('VUC-MINI CAMINHAO', 'Vuc Mini Caminhao'), ('BI TRUCK', 'Bi Truck'), ('TOCO', 'Toco'), ('3/4', 'Tres Quartos'), ('TRUCK', 'Truck'), ('VEICULO APOIO', 'Veiculo Apoio'), ('PASSAGEIRO', 'Passageiro'), ('PASSAGEIRO MOVEL', 'Passageiro Movel'), ('VW/24.280 CRM 6X2', 'Vw 24 280 Crm 6X2'), ('FIORINO', 'Fiorino'), ('HR', 'Hr')], max_length=20, null=True),
        ),
    ]
