# Generated by Django 3.2.19 on 2023-08-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicles_type_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='last_movement',
            field=models.DateField(null=True),
        ),
    ]
