# Generated by Django 4.2.5 on 2023-11-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_employees_email"),
        ("branches", "0001_initial"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacanciesControls",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("replacement", models.CharField(max_length=50, null=True)),
                ("salary_range", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(null=True)),
                ("observation", models.TextField(null=True)),
                ("work_schedule", models.TextField(null=True)),
                ("release_status", models.TextField(null=True)),
                ("date_expected_start", models.DateField()),
                ("date_reported", models.DateTimeField()),
                ("date_requested", models.DateField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("MÉDIA", "Media"),
                            ("ALTA", "Alta"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOVO", "Novo"),
                            ("EM ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDO", "Concluido"),
                            ("APROVADO", "Aprovado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="NOVO",
                        max_length=12,
                    ),
                ),
                (
                    "contract_mode",
                    models.CharField(
                        choices=[
                            ("JOVEM APRENDIZ", "Ja"),
                            ("CLT", "Clt"),
                            ("PESSOA JURÍDICA", "Pj"),
                            ("PCD", "Pcd"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("BORRACHARIA", "Borracharia"),
                            ("COMPRAS", "Compras"),
                            ("DEPARTAMENTO PESSOAL", "Departamento Pessoal"),
                            ("DESENVOLVIMENTO", "Desenvolvimento"),
                            ("EXPEDIÇÃO", "Expedicao"),
                            ("FATURAMENTO", "Faturamento"),
                            ("FINANCEIRO", "Financeiro"),
                            ("FISCAL", "Fiscal"),
                            ("FROTAS", "Frotas"),
                            ("JOVEM APRENDIZ", "Jovem Aprendiz"),
                            ("LIMPEZA", "Limpeza"),
                            ("MANUTENÇÃO", "Manutencao"),
                            ("MONITORAMENTO", "Monitoramento"),
                            ("OPERAÇÃO", "Operacao"),
                            ("PORTARIA", "Portaria"),
                            ("RECURSOS HUMANOS", "Recursos Humanos"),
                            ("RESERVA", "Reserva"),
                            ("TI", "Ti"),
                        ],
                        max_length=21,
                    ),
                ),
                (
                    "type_vacancy",
                    models.CharField(
                        choices=[
                            ("AUMENTO DE QUADRO", "Aumento Quadro"),
                            ("SUBSTITUIÇÃO", "Substituicao"),
                            ("TERCEIROS", "Terceiros"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[("BORA", "Bora"), ("JC", "Jc"), ("JSR", "Jsr")],
                        max_length=17,
                    ),
                ),
                (
                    "initiative",
                    models.CharField(
                        choices=[
                            ("EMPREGADO", "Empregado"),
                            ("EMPREGADOR", "Empregador"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("approval_manager", models.BooleanField(default=False)),
                ("comment_manager", models.TextField()),
                ("approval_regional_manager", models.BooleanField(default=False)),
                ("comment_regional_manager", models.TextField()),
                ("approval_rh", models.BooleanField(default=False)),
                ("comment_rh", models.TextField()),
                ("approval_director", models.BooleanField(default=False)),
                ("comment_director", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies_controls_author",
                        to="employees.employees",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies_controls",
                        to="branches.branches",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies_controls_recruiter",
                        to="employees.employees",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies_controls",
                        to="roles.roles",
                    ),
                ),
            ],
            options={
                "verbose_name": "VacancyControl",
                "verbose_name_plural": "VacanciesControls",
                "db_table": "vacancies_controls",
            },
        ),
    ]
