# Generated by Django 4.2.5 on 2023-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies_controls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="comment_director",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="comment_manager",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="comment_regional_manager",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="comment_rh",
            field=models.TextField(null=True),
        ),
    ]
