# Generated by Django 4.2.5 on 2023-11-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employees_email"),
        (
            "vacancies_controls",
            "0002_alter_vacanciescontrols_comment_director_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies_controls_author",
                to="employees.employees",
            ),
            preserve_default=False,
        ),
    ]
