# Generated by Django 4.2.5 on 2023-11-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies_controls", "0004_vacanciescontrols_email_director_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacanciescontrols",
            name="send_mail",
            field=models.BooleanField(default=False),
        ),
    ]
