# Generated by Django 4.2.5 on 2023-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies_controls", "0005_vacanciescontrols_send_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="approval_director",
            field=models.CharField(
                choices=[
                    ("NÃO RESPONDIDO", "Nao Respondido"),
                    ("APROVADO", "Aprovado"),
                    ("REPROVADO", "Reprovado"),
                ],
                default="NÃO RESPONDIDO",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="approval_manager",
            field=models.CharField(
                choices=[
                    ("NÃO RESPONDIDO", "Nao Respondido"),
                    ("APROVADO", "Aprovado"),
                    ("REPROVADO", "Reprovado"),
                ],
                default="NÃO RESPONDIDO",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="approval_regional_manager",
            field=models.CharField(
                choices=[
                    ("NÃO RESPONDIDO", "Nao Respondido"),
                    ("APROVADO", "Aprovado"),
                    ("REPROVADO", "Reprovado"),
                ],
                default="NÃO RESPONDIDO",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="approval_rh",
            field=models.CharField(
                choices=[
                    ("NÃO RESPONDIDO", "Nao Respondido"),
                    ("APROVADO", "Aprovado"),
                    ("REPROVADO", "Reprovado"),
                ],
                default="NÃO RESPONDIDO",
                max_length=14,
            ),
        ),
    ]
