# Generated by Django 4.2.5 on 2023-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vacancies_controls",
            "0006_alter_vacanciescontrols_approval_director_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vacanciescontrols",
            name="email_send_director",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="email_send_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="email_send_regional_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="email_send_rh",
            field=models.BooleanField(default=False),
        ),
    ]
