# Generated by Django 4.2.5 on 2023-11-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies_controls", "0008_remove_vacanciescontrols_send_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="company",
            field=models.CharField(
                choices=[("BORA", "Bora"), ("JC", "Jc"), ("JSR", "Jsr")], max_length=4
            ),
        ),
    ]
