# Generated by Django 4.2.5 on 2023-12-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vacancies_controls",
            "0010_alter_vacanciescontrols_comment_director_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="email_director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="email_manager",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="email_regional_manager",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="email_rh",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
