# Generated by Django 4.2.5 on 2023-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies_controls", "0011_alter_vacanciescontrols_email_director_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacanciescontrols",
            name="date_reported",
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="date_closed",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="date_exam",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="date_limit",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="date_vetta",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="motive",
            field=models.CharField(
                choices=[
                    ("DEMANDA FIM DE ANO", "Demanda Fim De Ano"),
                    ("NÃO PERFORMACE", "Nao Performace"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="quantity",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="vacanciescontrols",
            name="selected",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="recruiter",
            field=models.CharField(
                choices=[
                    ("LARYSSA RODRIGUES", "Laryssa Rodrigues"),
                    ("MELISSA COSTA", "Melissa Costa"),
                    ("PAULA SANTOS", "Paula Santos"),
                    ("RAQUEL SILVA", "Raquel Silva"),
                    ("THAYS ANDRADE", "Thays Andrade"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
