# Generated by Django 4.2.5 on 2023-12-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies_controls", "0012_remove_vacanciescontrols_date_reported_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacanciescontrols",
            name="quantity",
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
