# Generated by Django 3.2.19 on 2023-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('razao_social_motorista', models.CharField(max_length=100, unique=True)),
                ('cnpj_cpf', models.CharField(max_length=14, unique=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('tipo_cadastro', models.CharField(choices=[('CLIENTE', 'Cliente'), ('MOTORISTA', 'Motorista')], max_length=15)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='funcionarios.funcionarios')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientesFiliais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('saldo', models.IntegerField(default=0)),
                ('tipo_palete', models.CharField(choices=[('PBR', 'Pbr'), ('CHEP', 'Chep')], default='PBR', max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filiais.filiais')),
            ],
            options={
                'verbose_name': 'ClienteFilial',
                'verbose_name_plural': 'ClientesFiliais',
                'db_table': 'clientesfiliais',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='filiais',
            field=models.ManyToManyField(through='clientes.ClientesFiliais', to='filiais.Filiais', verbose_name='clientes'),
        ),
    ]
