# Generated by Django 3.2.19 on 2023-06-16 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiais', '0002_auto_20230508_0943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('razao_social_motorista', models.CharField(max_length=100)),
                ('observacao', models.TextField()),
                ('tipo_cadastro', models.CharField(choices=[('CLIENTE', 'Cliente'), ('MOTORISTA', 'Motorista')], max_length=15)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientesFiliais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('saldo', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filiais.filiais')),
            ],
            options={
                'verbose_name': 'ClienteFilial',
                'verbose_name_plural': 'ClientesFiliais',
                'db_table': 'clientesfiliais',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='filiais',
            field=models.ManyToManyField(through='clientes.ClientesFiliais', to='filiais.Filiais', verbose_name='clientes'),
        ),
    ]
