# Generated by Django 3.2.19 on 2023-06-19 11:14

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cnpj_cpf',
            field=models.CharField(default=1, max_length=14, validators=[clientes.models.only_int]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='razao_social_motorista',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
