# Generated by Django 3.2.19 on 2023-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20230619_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpj_cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
