# Generated by Django 3.2.19 on 2023-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_cnpj_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesfiliais',
            name='tipo_palete',
            field=models.CharField(choices=[('PBR', 'Pbr'), ('CHEP', 'Chep')], default='PBR', max_length=4),
        ),
    ]
