# Generated by Django 4.2.5 on 2023-11-07 08:02

from django.db import migrations, models
import django.db.models.deletion
import pj_thirteenths.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_employees_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PJThirteenths",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "months",
                    models.CharField(
                        max_length=2, validators=[pj_thirteenths.models.only_int]
                    ),
                ),
                ("date_payment", models.DateField()),
                ("value", models.FloatField()),
                ("send", models.BooleanField(default=False)),
                (
                    "type_payment",
                    models.CharField(
                        choices=[
                            ("ADIANTAMENTO", "Adiantamento"),
                            ("PAGAMENTO", "Pagamento"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pj_thirteenths_authors",
                        to="employees.employees",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pj_thirteenths_employees",
                        to="employees.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "PJThirteenth",
                "verbose_name_plural": "PJThirteenths",
                "db_table": "pj_thirteenths",
            },
        ),
    ]
