# Generated by Django 3.2.19 on 2023-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletesControles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('localizacao_atual', models.CharField(max_length=3)),
                ('destino', models.CharField(blank=True, max_length=3, null=True)),
                ('movimento_atual', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo_palete', models.CharField(choices=[('PBR', 'Pbr'), ('CHEP', 'Chep')], max_length=4)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paletes_controles', to='funcionarios.funcionarios')),
            ],
            options={
                'verbose_name': 'PaleteControle',
                'verbose_name_plural': 'PaletesControles',
                'db_table': 'paletes_controles',
            },
        ),
    ]
