# Generated by Django 3.2.19 on 2023-06-12 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletesControles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('localizacao_atual', models.CharField(blank=True, max_length=3, null=True)),
                ('movimento_atual', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo_palete', models.CharField(choices=[('PBR', 'Pbr'), ('CHEP', 'Chep')], default='PBR', max_length=4)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PaleteControle',
                'verbose_name_plural': 'PaletesControles',
                'db_table': 'paletes_controles',
            },
        ),
    ]
