# Generated by Django 3.2.19 on 2023-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletes_controles', '0002_auto_20230612_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paletescontroles',
            name='localizacao_atual',
            field=models.CharField(max_length=3),
        ),
    ]
