# Generated by Django 3.2.19 on 2023-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletes_controles', '0003_alter_paletescontroles_localizacao_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletescontroles',
            name='destino',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
