# Generated by Django 3.2.19 on 2023-08-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletsControls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('current_location', models.CharField(max_length=3)),
                ('destiny', models.CharField(blank=True, max_length=3, null=True)),
                ('current_movement', models.CharField(blank=True, max_length=25, null=True)),
                ('type_pallet', models.CharField(choices=[('PBR', 'Pbr'), ('CHEP', 'Chep')], max_length=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets_controls', to='employees.employees')),
            ],
            options={
                'verbose_name': 'PalletControl',
                'verbose_name_plural': 'PalletsControls',
                'db_table': 'pallets_controls',
            },
        ),
    ]
