# Generated by Django 3.2.19 on 2023-09-05 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PJComplements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('salary', models.FloatField()),
                ('allowance', models.FloatField(default=0)),
                ('college', models.FloatField(default=0)),
                ('housing_allowance', models.FloatField(default=0)),
                ('covenant_credit', models.FloatField(default=0)),
                ('others_credits', models.FloatField(default=0)),
                ('advance_money', models.FloatField(default=0)),
                ('covenant_discount', models.FloatField(default=0)),
                ('others_discounts', models.FloatField(default=0)),
                ('data_emission', models.DateTimeField(default=django.utils.timezone.now)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PJComplement',
                'verbose_name_plural': 'PJComplements',
                'db_table': 'pj_complements',
            },
        ),
    ]
