# Generated by Django 3.2.19 on 2023-08-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_complements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pjcomplements',
            name='date_payment',
        ),
    ]
