# Generated by Django 3.2.19 on 2023-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_complements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pjcomplements',
            old_name='other_credits',
            new_name='others_credits',
        ),
    ]
