# Generated by Django 4.2.5 on 2023-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pj_complements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pjcomplements",
            name="data_emission",
        ),
        migrations.AddField(
            model_name="pjcomplements",
            name="subsistence_allowance",
            field=models.FloatField(default=0),
        ),
    ]
