# Generated by Django 3.2.19 on 2023-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_complements', '0002_remove_pjcomplements_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjcomplements',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
