# Generated by Django 3.2.19 on 2023-09-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('epis_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIsSizes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(default='UNICO', max_length=5)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_minimum', models.PositiveIntegerField()),
                ('quantity_provisory', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_sizes', to='employees.employees')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_sizes', to='epis_items.episitems')),
            ],
            options={
                'verbose_name': 'EPISize',
                'verbose_name_plural': 'EPIsSizes',
                'db_table': 'epis_sizes',
            },
        ),
    ]
