# Generated by Django 4.2.5 on 2023-12-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_employees_email"),
        ("branches", "0002_alter_branches_name"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("replacement", models.CharField(max_length=50, null=True)),
                ("salary_range", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(null=True)),
                ("observation", models.TextField(null=True)),
                ("selected", models.CharField(blank=True, max_length=255, null=True)),
                ("work_schedule", models.TextField(null=True)),
                ("release_status", models.TextField(null=True)),
                ("quantity", models.SmallIntegerField(default=1, null=True)),
                ("date_expected_start", models.DateField()),
                ("date_requested", models.DateField(auto_now=True)),
                ("date_vetta", models.DateField(null=True)),
                ("date_exam", models.DateField(null=True)),
                ("date_closed", models.DateField(null=True)),
                ("date_limit", models.DateField(null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("MÉDIA", "Media"),
                            ("ALTA", "Alta"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOVO", "Novo"),
                            ("EM ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDO", "Concluido"),
                            ("APROVADO", "Aprovado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="NOVO",
                        max_length=12,
                    ),
                ),
                (
                    "contract_mode",
                    models.CharField(
                        choices=[
                            ("JOVEM APRENDIZ", "Ja"),
                            ("CLT", "Clt"),
                            ("PESSOA JURÍDICA", "Pj"),
                            ("PCD", "Pcd"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("BORRACHARIA", "Borracharia"),
                            ("COMPRAS", "Compras"),
                            ("DEPARTAMENTO PESSOAL", "Departamento Pessoal"),
                            ("DESENVOLVIMENTO", "Desenvolvimento"),
                            ("EXPEDIÇÃO", "Expedicao"),
                            ("FATURAMENTO", "Faturamento"),
                            ("FINANCEIRO", "Financeiro"),
                            ("FISCAL", "Fiscal"),
                            ("FROTAS", "Frotas"),
                            ("JOVEM APRENDIZ", "Jovem Aprendiz"),
                            ("LIMPEZA", "Limpeza"),
                            ("MANUTENÇÃO", "Manutencao"),
                            ("MONITORAMENTO", "Monitoramento"),
                            ("OPERAÇÃO", "Operacao"),
                            ("PORTARIA", "Portaria"),
                            ("RECURSOS HUMANOS", "Recursos Humanos"),
                            ("RESERVA", "Reserva"),
                            ("TI", "Ti"),
                        ],
                        max_length=21,
                    ),
                ),
                (
                    "type_vacancy",
                    models.CharField(
                        choices=[
                            ("AUMENTO DE QUADRO", "Aumento Quadro"),
                            ("SUBSTITUIÇÃO", "Substituicao"),
                            ("TERCEIROS", "Terceiros"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[("BORA", "Bora"), ("JC", "Jc"), ("JSR", "Jsr")],
                        max_length=4,
                    ),
                ),
                (
                    "initiative",
                    models.CharField(
                        choices=[
                            ("EMPREGADO", "Empregado"),
                            ("EMPREGADOR", "Empregador"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "recruiter",
                    models.CharField(
                        choices=[
                            ("LARYSSA RODRIGUES", "Laryssa Rodrigues"),
                            ("MELISSA COSTA", "Melissa Costa"),
                            ("PAULA SANTOS", "Paula Santos"),
                            ("RAQUEL SILVA", "Raquel Silva"),
                            ("THAYS ANDRADE", "Thays Andrade"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "motive",
                    models.CharField(
                        choices=[
                            ("DEMANDA FIM DE ANO", "Demanda Fim De Ano"),
                            ("NÃO PERFORMACE", "Nao Performace"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "approval_manager",
                    models.CharField(
                        choices=[
                            ("NÃO RESPONDIDO", "Nao Respondido"),
                            ("APROVADO", "Aprovado"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="NÃO RESPONDIDO",
                        max_length=14,
                    ),
                ),
                ("comment_manager", models.TextField(blank=True, null=True)),
                (
                    "email_manager",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email_send_manager", models.BooleanField(default=False)),
                (
                    "approval_regional_manager",
                    models.CharField(
                        choices=[
                            ("NÃO RESPONDIDO", "Nao Respondido"),
                            ("APROVADO", "Aprovado"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="NÃO RESPONDIDO",
                        max_length=14,
                    ),
                ),
                ("comment_regional_manager", models.TextField(blank=True, null=True)),
                (
                    "email_regional_manager",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email_send_regional_manager", models.BooleanField(default=False)),
                (
                    "approval_rh",
                    models.CharField(
                        choices=[
                            ("NÃO RESPONDIDO", "Nao Respondido"),
                            ("APROVADO", "Aprovado"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="NÃO RESPONDIDO",
                        max_length=14,
                    ),
                ),
                ("comment_rh", models.TextField(blank=True, null=True)),
                ("email_rh", models.CharField(blank=True, max_length=100, null=True)),
                ("email_send_rh", models.BooleanField(default=False)),
                (
                    "approval_director",
                    models.CharField(
                        choices=[
                            ("NÃO RESPONDIDO", "Nao Respondido"),
                            ("APROVADO", "Aprovado"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="NÃO RESPONDIDO",
                        max_length=14,
                    ),
                ),
                ("comment_director", models.TextField(blank=True, null=True)),
                (
                    "email_director",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email_send_director", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies_author",
                        to="employees.employees",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies",
                        to="branches.branches",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies",
                        to="roles.roles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy",
                "verbose_name_plural": "Vacancies",
                "db_table": "vacancies",
            },
        ),
    ]
