# Generated by Django 4.2.5 on 2023-10-04 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xmls.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Xmls",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("date_published", models.DateTimeField(auto_now=True)),
                ("date_emission", models.DateTimeField()),
                ("nf", models.IntegerField()),
                ("sender", models.CharField(max_length=200)),
                ("recipient", models.CharField(max_length=200)),
                ("weight", models.FloatField()),
                ("volume", models.IntegerField()),
                ("value_nf", models.FloatField()),
                ("district", models.CharField(max_length=50)),
                (
                    "cep",
                    models.CharField(max_length=8, validators=[xmls.models.only_int]),
                ),
                ("county", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                ("printed", models.BooleanField(default=False)),
                ("xml_file", models.FileField(upload_to="xmls/%Y/%m/%d")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="xmls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Xml",
                "verbose_name_plural": "Xmls",
                "db_table": "xmls",
            },
        ),
    ]
