# Generated by Django 4.2.5 on 2023-10-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
        ("xmls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xmls",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="xmls",
                to="employees.employees",
            ),
        ),
    ]
