# Generated by Django 3.2.19 on 2023-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_complementos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjcomplementos',
            name='adiantamento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pjcomplementos',
            name='auxilio_moradia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pjcomplementos',
            name='credito_convenio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pjcomplementos',
            name='desconto_convenio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pjcomplementos',
            name='faculdade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pjcomplementos',
            name='outros_creditos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pjcomplementos',
            name='outros_descontos',
            field=models.FloatField(default=0),
        ),
    ]
