# Generated by Django 3.2.19 on 2023-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_complementos', '0002_auto_20230626_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjcomplementos',
            name='ajuda_custo',
            field=models.FloatField(default=0),
        ),
    ]
