# Generated by Django 3.2.19 on 2023-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesDismissals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dismissal_date', models.DateField()),
                ('dismissal_motive', models.TextField()),
            ],
            options={
                'verbose_name': 'EmployeeDismissal',
                'verbose_name_plural': 'EmployeesDismissals',
                'db_table': 'employees_dismissals',
            },
        ),
    ]
