# Generated by Django 4.2.5 on 2023-11-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokensEmails",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("email", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("date_expiration", models.DateTimeField()),
            ],
            options={
                "verbose_name": "TokenEmail",
                "verbose_name_plural": "TokensEmails",
                "db_table": "tokens_emails",
            },
        ),
    ]
