# Generated by Django 4.2.5 on 2023-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens_emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokensemails",
            name="date_emission",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
